serviceMaps:
 serviceName: tl-calculator
 mappings:
 - version: 1.0
   description: Persists tradeLicense calculation details in EG_TL_CALCULATION  table
   fromTopic: save-tl-calculation
   isTransaction: true
   queryMaps:

       - query: INSERT INTO eg_tl_calculation(id,tenantId,consumercode,type,slabid,createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?,);
         basePath: Calculations.*
         jsonMaps:
          - jsonPath: $.Calculations.*.id

          - jsonPath: $.Calculations.*.tenantId

          - jsonPath: $.Calculations.*.consumercode

          - jsonPath: $.Calculations.*.type

          - jsonPath: $.Calculations.*.slabid

          - jsonPath: $.Calculations.*.createdby

          - jsonPath: $.Calculations.*.lastmodifiedby

          - jsonPath: $.Calculations.*.createdtime

          - jsonPath: $.Calculations.*.lastmodifiedtime

